using SequenceAssemblerLogic.ProteinAlignmentCode;
using System;
using System.Collections.Generic;

namespace ProteinAlignmentCode
{

    class Program
    {
        static void Main(string[] args)
        {
            string small = "VEEPLIK";
            string large = "EVQLVESGGGLVQPGGSLRLSCAASGFNIKDTYIHWVRQAPGKGLEWVARIYPTNGYTRYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCSRWGGDGFYAMDYWGQGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK";
            string sourceOrigins = "psm/denovo";
            SequenceAligner sequenceAligner = new SequenceAligner();
            var result = sequenceAligner.AlignSequences(small, large, sourceOrigins) ;
            Console.WriteLine(result);
            Console.WriteLine($"Identidade: {result.Identity}");
            Console.WriteLine($"Sequência Alinhada (Grande): {result.AlignedLargeSequence}");
            Console.WriteLine($"Sequência Alinhada (Pequena): {result.AlignedSmallSequence}");
            Console.WriteLine();

            string bsa = "MKWVTFISLLLLFSSAYSRGVFRRDTHKSEIAHRFKDLGEEHFKGLVLIAFSQYLQQCPFDEHVKLVNELTEFAKTCVADESHAGCEKSLHTLFGDELCKVASLRETYGDMADCCEKQEPERNECFLSHKDDSPDLPKLKPDPNTLCDEFKADEKKFWGKYLYEIARRHPYFYAPELLYYANKYNGVFQECCQAEDKGACLLPKIETMREKVLASSARQRLRCASIQKFGERALKAWSVARLSQKFPKAEFVEVTKLVTDLTKVHKECCHGDLLECADDRADLAKYICDNQDTISSKLKECCDKPLLEKSHCIAEVEKDAIPENLPPLTADFAEDKDVCKNYQEAKDAFLGSFLYEYSRRHPEYAVSVLLRLAKEYEATLEECCAKDDPHACYSTVFDKLKHLVDEPQNLIKQNCDQFEKLGEYGFQNALIVRYTRKVPQVSTPTLVEVSRSLGKVGTRCCTKPESERMPCTEDYLSLILNRLCVLHEKTPVSEKVTKCCTESLVNRRPCFSALTPDETYVPKAFDEKLFTFHADICTLPDTEKQIKKQTALVELLKHKPKATEEQLKTVMENFVAFVDKCCAADDKEACFAVEGPKLVVSTQTALA";
            string contigs = "YLYEIAR";
            string sourceOrigin = "psm/denovo";
            SequenceAligner sa = new SequenceAligner();

            var aln = sa.AlignSequences(bsa, contigs, sourceOrigin);


            Console.WriteLine("dONE");

        }

    }

}
